name: 'Bump Version and publish package'

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  deliver-package:
    # The type of runner that the job will run on
    name: 'Deliver package'
    runs-on: ubuntu-latest
    needs: bump-version

    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'origin/master'

      - run: git checkout HEAD
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@beercode'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTION_TOKEN }}
      # - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
      # - run: |
      #     cat .npmrc
      - name: Yarn install
        run: yarn install
        env:
          NPM_CONFIG_USERCONFIG: .npmrc.ci
          NODE_AUTH_TOKEN: ${{ secrets.ACTION_TOKEN }}
      - name: Run yarn build and publish lib
        run: yarn publish-lib

        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTION_TOKEN }}
